### ISSUE TITLE
Configuration failed, will retry: 400, message

### ISSUE THREAD

**Issue by bernox89** [augustas2/eldes#44]
Hello, do you have any news regarding the resolution of this problem, when adding my eldes account I receive this error:

No devices or entities
Configuration failed, will retry: 400, message='', url='https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=''myimei'''

**Comment by augustas2** [comment]
The latest update should resolve this issue.
Please update via HACS or manually:
https://github.com/augustas2/eldes/releases/tag/v2.0.0

**Comment by bernox89** [comment]
Hi, I read now, I'll update you as soon as possible, as I'm doing a new installation of home assistant. Thanks a lot anyway for the support for Eldes products.

**Comment by MotiejusK** [comment]
Still an issue on 2.0.

![Image](https://github.com/user-attachments/assets/d526b594-b9a2-4b92-bd36-1b86730ac1d4)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/__init__.py", line 46, in async_setup_entry
    selected_imei = entry.data[CONF_DEVICE_IMEI]
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'device_imei'

**Comment by augustas2** [comment]
> Still an issue on 2.0.
> 
> ![Image](https://github.com/user-attachments/assets/d526b594-b9a2-4b92-bd36-1b86730ac1d4)
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/eldes_alarm/**init**.py", line 46, in async_setup_entry selected_imei = entry.data[CONF_DEVICE_IMEI] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^ KeyError: 'device_imei'

That's completely different issue you are writing about. You can clearly see from the log you provided.
Have you deleted old integration version and installed it from scratch?

**Comment by augustas2** [comment]
No answer. Closing.

> ⚠️ **Deprecation Notice**  
> I am no longer an owner of any Eldes products and will not be maintaining or developing this integration further.  
> If you have development experience and are interested in taking over maintenance of this project, please open an issue or contact me via GitHub.
